### ISSUE TITLE
Fix ids in the crawler source table.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-db#110]
https://github.com/internetofwater/nldi-db/blob/master/liquibase/changeLogs/nldi/nldi_data/update_crawler_source/crawler_source.tsv should have sequential and non-gapped ids.

**Comment by webb-ben** [comment]
Functioning crawler source table (for current artifacts): https://github.com/internetofwater/nldi-db/blob/master/database/demo/crawler_source.tsv

**Comment by dblodgett-usgs** [comment]
Cool. Can you take on this issue quick?
